import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiClient } from "../../shared/api/client";
import type { AnalysisFact } from "./insightTypes";

export interface AiInsight {
  id: string;
  sectorId: string | null;
  sectorName: string | null;
  holdingId: string | null;
  generatedAt: string;
  summary: string;
  sourceUrls: string[];
  /** Empty for sector-level insights, which are still stubbed. */
  facts: AnalysisFact[];
}

export function useInsights() {
  return useQuery({
    queryKey: ["insights"],
    queryFn: async () => (await apiClient.get<AiInsight[]>("/insights")).data,
  });
}

export function useGenerateInsight() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (sectorId: string) =>
      (await apiClient.post<AiInsight>("/insights/generate", { sectorId })).data,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["insights"] }),
  });
}

export function useHoldingInsights(holdingId: string) {
  return useQuery({
    queryKey: ["holdings", holdingId, "insights"],
    queryFn: async () => (await apiClient.get<AiInsight[]>(`/holdings/${holdingId}/insights`)).data,
  });
}

// Holding analyses are generated by streamHoldingInsight() rather than a mutation —
// the run takes minutes and reports progress, which useMutation has no shape for.
