import { useQuery } from "@tanstack/react-query";
import { apiClient } from "../../shared/api/client";
import type { AnalysisFact } from "./insightTypes";

export type InsightScope = "Holding" | "Portfolio" | "MarketUkraine" | "MarketGlobal";

export interface AiInsight {
  id: string;
  scope: InsightScope;
  holdingId: string | null;
  /** Name of the analysed asset — still filled in after the asset was deleted. */
  holdingName: string | null;
  isHoldingDeleted: boolean;
  generatedAt: string;
  summary: string;
  sourceUrls: string[];
  /** Empty on rows written before the pipeline produced structured facts. */
  facts: AnalysisFact[];
}

/** The whole archive: every analysis ever run, portfolio-level and per-asset alike. */
export function useInsights() {
  return useQuery({
    queryKey: ["insights"],
    queryFn: async () => (await apiClient.get<AiInsight[]>("/insights")).data,
  });
}

export function useHoldingInsights(holdingId: string) {
  return useQuery({
    queryKey: ["holdings", holdingId, "insights"],
    queryFn: async () => (await apiClient.get<AiInsight[]>(`/holdings/${holdingId}/insights`)).data,
  });
}

// Holding analyses are generated by streamHoldingInsight() rather than a mutation —
// the run takes minutes and reports progress, which useMutation has no shape for.
