<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapitalTracker.Application\CapitalTracker.Application.csproj" />
    <ProjectReference Include="..\CapitalTracker.Infrastructure\CapitalTracker.Infrastructure.csproj" />
    <ProjectReference Include="..\CapitalTracker.Domain\CapitalTracker.Domain.csproj" />
  </ItemGroup>

</Project>
